-- =============================================================================
-- 02_roles_grants.sql
-- Creates three roles that mirror a real data-team separation of concerns:
--   LOADER     → writes raw data to RAW schema only
--   TRANSFORMER → reads RAW, writes ANALYTICS (used by dbt)
--   REPORTER    → reads ANALYTICS only (used by Streamlit / BI tools)
-- Run as ACCOUNTADMIN after 01_database_warehouse.sql.
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ECOMMERCE_WH;

-- ── Role creation ─────────────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;
CREATE ROLE IF NOT EXISTS REPORTER;

-- ── Warehouse access ──────────────────────────────────────────────────────────
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE LOADER;
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE ECOMMERCE_WH TO ROLE REPORTER;

-- ── Database-level usage ──────────────────────────────────────────────────────
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE LOADER;
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ECOMMERCE_DB TO ROLE REPORTER;

-- ── LOADER: full access to RAW schema only ────────────────────────────────────
GRANT USAGE  ON SCHEMA ECOMMERCE_DB.RAW TO ROLE LOADER;
GRANT CREATE TABLE, CREATE STAGE ON SCHEMA ECOMMERCE_DB.RAW TO ROLE LOADER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE
    ON ALL TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE LOADER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE
    ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE LOADER;

-- ── TRANSFORMER: read RAW, write ANALYTICS ────────────────────────────────────
GRANT USAGE  ON SCHEMA ECOMMERCE_DB.RAW       TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.RAW TO ROLE TRANSFORMER;

GRANT USAGE  ON SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE
    ON SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL PRIVILEGES
    ON ALL TABLES IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL PRIVILEGES
    ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE TRANSFORMER;

-- CI schema (TRANSFORMER can drop/create freely)
GRANT USAGE ON SCHEMA ECOMMERCE_DB.CI TO ROLE TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA ECOMMERCE_DB.CI TO ROLE TRANSFORMER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ECOMMERCE_DB.CI TO ROLE TRANSFORMER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.CI TO ROLE TRANSFORMER;

-- ── REPORTER: read-only on ANALYTICS + STAGING ───────────────────────────────
GRANT USAGE  ON SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES   IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON ALL VIEWS    IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ECOMMERCE_DB.ANALYTICS TO ROLE REPORTER;

-- STAGING views (needed by Streamlit dashboard for payment breakdown chart)
GRANT USAGE  ON SCHEMA ECOMMERCE_DB.STAGING TO ROLE REPORTER;
GRANT SELECT ON ALL VIEWS    IN SCHEMA ECOMMERCE_DB.STAGING TO ROLE REPORTER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ECOMMERCE_DB.STAGING TO ROLE REPORTER;

-- ── Assign roles to your user ─────────────────────────────────────────────────
-- Replace YOUR_USERNAME with your actual Snowflake username
GRANT ROLE LOADER      TO USER OPENSHAD26;
GRANT ROLE TRANSFORMER TO USER OPENSHAD26;
GRANT ROLE REPORTER    TO USER OPENSHAD26;

-- ── Verification ──────────────────────────────────────────────────────────────
SHOW ROLES LIKE 'LOADER';
SHOW ROLES LIKE 'TRANSFORMER';
SHOW ROLES LIKE 'REPORTER';
